name: Atualiza Cotação do Dólar no README

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Atualizar README com cotação atual
        run: python atualiza_readme.py

      - name: Commit e push das mudancas
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "juanmmendes"
          git config user.email "juanmmendes@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/juanmmendes/ConsumoApiCotacao.git
          git add README.md
          git commit -m "🤖 Atualização automática da cotação do dólar"
          git push

